In [1]:
import numpy as np

In [2]:
x=np.array([1,2,3,4])

In [3]:
print(type(x))

<class 'numpy.ndarray'>


In [4]:
#type function tell us the class of variable and the class of numpy array is numpy.ndarray

In [5]:
#numpy array only contain one type of data type

In [6]:
%timeit np.arange(1,9)**4

3.23 μs ± 255 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [7]:
#actually %timeit function give the time taken by the command

In [8]:
print(x.ndim)

1


In [9]:
y=np.array([[1,2,3,4],[2,3,4,5]])

In [10]:
print(y.ndim)

2


In [11]:
z=np.array([1,2,3,4], ndmin=10)
print(z)
print(z.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


In [12]:
#actually ndim tell the dimension of the array and ndmin is use to make the array of n-dimension

In [13]:
ar_zero=np.zeros((3,4))
print(ar_zero)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [14]:
#np.zeros function is use to make the array of any dimension with all entries filled with zero 

In [15]:
#similarly np.ones is use to make the array of any dimension with all entries filled with one

In [16]:
ar_emp = np.empty((2,3))
print(ar_emp)

[[1.e-323 0.e+000 0.e+000]
 [0.e+000 0.e+000 0.e+000]]


In [17]:
ar_emp2 = np.empty((3,4))
print(ar_emp2)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [18]:
#np.empty function is use to make the array of empty values means any random values and if any array in the program exist with the same dimension then it contain the value of that array

In [19]:
ar_dia = np.eye(3)
print(ar_dia)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [20]:
#np.eye function is used to make the identity matrix of n dimension, it can be used in both sqaure matrix and non-square matrix

In [21]:
ar_rn= np.arange(4)
print(ar_rn)

[0 1 2 3]


In [22]:
#here arange function is ussed as saame as range function in python

In [23]:
ar_lin=np.linspace(0,20,num=5)
print(ar_lin)

[ 0.  5. 10. 15. 20.]


In [24]:
#np.linspace function is a type of arange function in which elements are printing in a particular gap

In [25]:
#rand() function is use to randomly generate the number between 0 and 1 of any dimension
var= np.random.rand(4,4)
print(var)

[[0.48391668 0.62117189 0.45390406 0.82912978]
 [0.52222836 0.39539812 0.33804829 0.82224872]
 [0.80023425 0.94739047 0.84139176 0.46670157]
 [0.60715087 0.21106784 0.36412789 0.54625933]]


In [26]:
#randn() function is use to generate a random value close to zero. this may return positive or negative numbers as well.
var1=np.random.randn(3,4)
print(var1)

[[-0.55865157  0.88908672  1.79450321 -0.30339447]
 [-1.02818941  0.20423167 -1.73538137 -0.56745948]
 [ 0.09777439  2.39038117 -0.32426899 -0.31702766]]


In [27]:
#ranf() function is use to generate a random floats value in the half open interval [0.0, 1.0), make sure it doesn't accept m*n dimension.
var2=np.random.ranf(4)
print(var2)

[0.42523172 0.69946628 0.25811193 0.86310051]


In [28]:
#randint function is use to generate the number between a particular range you can allot, this function is cal as same as range function means (initial value , final value , no. of values you want between them)
var3=np.random.randint(3,11,2)
print(var3)

[10 10]


In [29]:
#dtype function is used to identify the data type of a variable
var4=np.array(["a"])
print(var4.dtype)

<U1


In [30]:
#<U1 is a string data type

In [31]:
#dtype is also use to converting the data type 
z=np.array([1,2,3,4], dtype= np.int8)
print(z.dtype)
print(z)

int8
[1 2 3 4]


In [32]:
#therer is one more function astype(reqdatatype) to convert the data type
z1=np.array([1,2,3,4])
new_1=z1.astype(float)
print(z1)
print(new_1)

[1 2 3 4]
[1. 2. 3. 4.]


In [33]:
#we can do add operation , we can add all numbers of an array with a number or also can add two array simply by + operator and also by using add function and we can do it to use any operator like mod or reciprocal 
#naya=z1+3
naya = np.add(z1,3)
print(naya)

[4 5 6 7]


In [34]:
print(z1+z1)

[2 4 6 8]


In [35]:
#there are many functions in numpy like min , max etc
#and there is a function called argmin for min and argmax for max which tells the position of minimum and maximum element present in the array
bb=np.array([1,2,3,4,5,3,2])
print("min: ",np.min(bb),np.argmin(bb))

min:  1 0


In [36]:
bb1= np.array([[2,1,3],[9,5,6]])
print(np.min(bb1, axis=0))

[2 1 3]


In [37]:
#axix 0 is actually use for rows and axis 1 is use for columns 

In [38]:
#cumsum function is use to forward addition like 1 , 2, 3 = 1 ,3,6

In [39]:
#nditer() function is used to iterate all numbers of any dimension of matrix
bb2 = np.array([[[9,8,7],[6,5,4]]])
print(bb2)
print(bb2.ndim)

for i in np.nditer(bb2):
    print(i)

[[[9 8 7]
  [6 5 4]]]
3
9
8
7
6
5
4


In [40]:
#ndenumerate is a function which print all the elements of the array of any dimension with indexing
bb3 = np.array([[[9,8,7],[6,5,4]]])
print(bb3)
print(bb3.ndim)

for i,d in np.ndenumerate(bb3):
    print(i,d)

[[[9 8 7]
  [6 5 4]]]
3
(0, 0, 0) 9
(0, 0, 1) 8
(0, 0, 2) 7
(0, 1, 0) 6
(0, 1, 1) 5
(0, 1, 2) 4


In [41]:
#copy function is used to copy the data of the array
ar=np.array([1,2,3,4])
co=ar.copy()
ar[1]=20
print(ar)
print(co)

[ 1 20  3  4]
[1 2 3 4]


In [42]:
ar1=np.array([1,2,3,4])
vi=ar1.view()
ar1[2]=20
print(ar1)
print(vi)

[ 1  2 20  4]
[ 1  2 20  4]


In [43]:
#the difference between copy and view is in copy if we change the original data no effect show in copied data  but if we use view then after change in either original or viewed data , that effect both the data

#JOin array

In [44]:
#be remember we can join two array if and only if both the array have the same number of elements

In [45]:
cc1=np.array([1,2,3,4])
cc2=np.array([5,6,7,8])
cc3=np.concatenate((cc1, cc2))
print(cc3)

[1 2 3 4 5 6 7 8]


In [46]:
# for two and three dimension you have to tell that from where it have to merge means from axis =0 or axis=1
cc4=np.array([[1,2],[3,4]])
cc5=np.array([[5,6],[7,8]])
cc6=np.concatenate((cc4, cc5),axis=1)
print(cc6)

[[1 2 5 6]
 [3 4 7 8]]


In [47]:
#similarly we have a stack function which also do the same function but in stack we have 3 new function hstack, vstack, dstack these three join the 2 or 3 or any dimension array with rowise, columnwise and heightwise respectively

#split

In [48]:
cc7=np.array_split(cc1,2)
print(cc7)

[array([1, 2]), array([3, 4])]


In [49]:
#remeber that split return the array in form of list

In [50]:
#where function give the indices of the elements 
dd = np.array([4,5,2,4,5,6,2,1,4,5])
dd1=np.where(dd==5)
print(dd1)

(array([1, 4, 9], dtype=int64),)


In [51]:
#searchsorted function tell the place where the given element can be inserted in a given sortwd arrray
dd2 = np.array([1,2,3,4,6,7,8,10,11])
dd3=np.searchsorted(dd2,[5,9],side="right")
print(dd3)

[4 7]


In [52]:
#np.sort function is use to sort the array with numbers and string also, it can also work for 2d array and 3d aarray


Filter array

In [53]:
#by filter function you can filter the elements by using another array of having true and false
dd4=np.array(["a","b","c","d"])
f=[True, False, False, True]
new_a=dd4[f]
print(new_a)

['a' 'd']


In [54]:
#np.random.shuffle shuffle the array in any form

In [55]:
#np.unique give the unique element of the array 
dd5=np.array([1,2,3,2,4,2,4,5,2,6,7,7,9,8,6,4,1,3])
dd6=np.unique(dd5, return_index=True, return_counts=True)
print(dd6)

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), array([ 0,  1,  2,  4,  7,  9, 10, 13, 12], dtype=int64), array([2, 4, 2, 3, 1, 2, 2, 1, 1], dtype=int64))


In [56]:
#np.resize function can chnage the dimension of the array
ss=np.resize(dd5,(2,3))
print(ss)
print()
print(ss.flatten(order="F"))

[[1 2 3]
 [2 4 2]]

[1 2 2 4 3 2]


In [58]:
#np.insert can insert elements in the array but floating pnumbers cannot insert it can also insert in row and columns both
#np.append can insert elements in row and columns both and it can also insert floating numbers
#np.delete can delete the numbers whose indexing you will pass

In [59]:
#there are many function related to matrix 
#for transpose --> np.transpose(var) or var.T
#for swapaxes--> np.swapaxes(var)
#for inverse--> np.linalg.inv(var)
#for powerr of the matrix--> np.linalg.matrix_power(var,power)
#for determinant of the matrix --> np.linalg.det(var)

In [62]:
cpu=np.array([[1,2],[4,5]])
cpu2=np.array([[6,5],[4,3]])
print(np.dot(cpu,cpu2))

[[14 11]
 [44 35]]
